sources:
  - ./Tests/SwiftTemplatesTests/Context
templates:
  - ./Templates
output:
  ./Tests/SwiftTemplatesTests/Generated
args:
  import: "Foundation.NSDate;Foundation.NSURL"
  testable_import: "ModuleA;ModuleB"
