name: Test

on:
  push:

env:
  DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
  BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}

jobs:
  test:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby and `bundle install`
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - name: Cache CocoaPods files
        uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Install Sourcery
        run: bundle exec pod install
      - run: xcodebuild test -project SwiftTemplates.xcodeproj -scheme SwiftTemplatesTests

