name: Test

on:
  push:

env:
  DEVELOPER_DIR: /Applications/Xcode_14.0.1.app/Contents/Developer
  BUNDLE_GITHUB__COM: ${{ secrets.BUNDLE_GITHUB__COM }}

jobs:
  test:
    runs-on: macos-12
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Cache Swift Packages
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Run Sourcery
        run: swift run sourcery --config .sourcery.yml --disableCache --verbose
      - name: Run Test
        run: swift test

